/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ListJNI */

#ifndef _Included_ListJNI
#define _Included_ListJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ListJNI
 * Method:    newList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ListJNI_newList
  (JNIEnv *, jobject);

/*
 * Class:     ListJNI
 * Method:    add
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ListJNI_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     ListJNI
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ListJNI_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     ListJNI
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ListJNI_size
  (JNIEnv *, jobject);

/*
 * Class:     ListJNI
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ListJNI_clear
  (JNIEnv *, jobject);

/*
 * Class:     ListJNI
 * Method:    contains
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ListJNI_contains
  (JNIEnv *, jobject, jint);

/*
 * Class:     ListJNI
 * Method:    indexOf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ListJNI_indexOf
  (JNIEnv *, jobject, jint);

/*
 * Class:     ListJNI
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ListJNI_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     ListJNI
 * Method:    lastIndexOf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ListJNI_lastIndexOf
  (JNIEnv *, jobject, jint);

/*
 * Class:     ListJNI
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ListJNI_remove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
